# Generated by Django 3.2.5 on 2023-02-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isPublished', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(max_length=4096)),
                ('githubLink', models.CharField(max_length=4096)),
            ],
        ),
    ]
